person1 = input("Input name: ")
person2 = input("Input another name: ")
person3 = input("Input yet another name: ")
person4 = input("Input yet another name: ")
person5 = input("Input yet another name: ")
person6 = input("Input yet another name: ")
person7 = input("Input yet another name: ")
person8 = input("Input yet another name: ")
person9 = input("Input yet another name: ")
person10 = input("Input yet another name: ")

print(person10)
print(person9)
print(person8)
print(person7)
print(person6)
print(person5)
print(person4)
print(person3)
print(person2)
print(person1)